### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by rohanagarwal94** [rohanagarwal94/Hardware-testing#5]
Points to remember before generating a PR-
Include the screenshots of the app.
Mention the license of the app (MIT).
A short description of each point mentioned already.
A link to the dropbox.
Contribution guidelines.

**Comment by mridulg** [comment]
@rohanagarwal94 on it.

**Comment by mridulg** [comment]
@rohanagarwal94 please check and let me know if any changes are required.
